name: Android CI
on:
  push:
    branches: -master
      -staging
      -dev
  pull_request:
    branches: [master]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Write permission for Gradlew
        run: chmod +x ./gradlew
      - name: set up JDK 1.8
        uses: action/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Dev Application
        run: ./gradlew buildDevDebug
      - name: Upload Apk Artifact
        uses: actions/upload-artifact@v2
        with:
          name: devDebug Application
          path: ./app/build/outputs/apk/dev/debug/app-dev-debug.apk
