name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
    - '**'
    - '.github/workflows/Android-Action.yml'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build          
  upload-app-distribution:
   name: "Upload APK to Firebase App Distribution"
   #The type of runner that the job will run on
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Download Stored Artifact
      uses: actions/download-artifact@v2
      with:
         name: app-debug
         
    - name: Upload APK
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
      with:
        #Acquire from Firebase Console.Project Overview Project Settigns Under the App area you will see"App ID`
        appId: ${{secrets.FIREBASE ANDROID APP_ID}}
        #Generate using Firebase CLI.Command to run'firebase login:ci".
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: qa-internal#Speciyagroup you want the app to be distributed to
        file: app-debug.apk
